version: "3.8"
services:
  streamlit:
    image: python:3.10-slim
    container_name: iris_streamlit2
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8501:8501"
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             streamlit run app.py --server.address=0.0.0.0"